# Generated by Django 6.0.1 on 2026-01-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('hexlet', 'Hexlet'), ('stepik', 'Stepik'), ('manual', 'Вручную')], default='hexlet', max_length=20)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('start_end', models.CharField(blank=True, max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('learners_count', models.IntegerField(default=0)),
                ('time_to_complete', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('reviews_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
