# Generated by Django 6.0.1 on 2026-01-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на курс'),
        ),
    ]
